### ISSUE TITLE
NetBSD: conflict with libc `heapsort()` and `mergesort()`

### ISSUE THREAD

**Issue by 0-wiz-0** [yugr/sortcheck#1] opened 2024-12-21 18:19 UTC
For fun, I tried compiling sortcheck on NetBSD (since it might actually work), but the default compiler warning/error flags break the build for me because NetBSD libc provides `heapsort()` and `mergesort()` functions [returning an int](https://man.netbsd.org/heapsort.3).
```
cc -D_GNU_SOURCE -Iinclude -fPIC -g -fvisibility=hidden -Wall -Wextra -Werror -O2 -c src/sortchecker.c -o bin/sortchecker.o
In file included from src/sortchecker.c:41:
/usr/include/stdlib.h:319:10: error: conflicting types for ‘heapsort’; have ‘int(void *, size_t,  size_t,  int (*)(const void *, const void *))’ {aka ‘int(void *, long unsigned int,  long unsigned int,  int (*)(const void *, const void *))’}
  319 | int      heapsort(void *, size_t, size_t, int (*)(const void *, const void *));
      |          ^~~~~~~~
src/sortchecker.c:26:13: note: previous declaration of ‘heapsort’ with type ‘void(void *, size_t,  size_t,  int (*)(const void *, const void *))’ {aka ‘void(void *, long unsigned int,  long unsigned int,  int (*)(const void *, const void *))’}
   26 | EXPORT void heapsort(void *data, size_t n, size_t sz, cmp_fun_t cmp);
      |             ^~~~~~~~
/usr/include/stdlib.h:320:10: error: conflicting types for ‘mergesort’; have ‘int(void *, size_t,  size_t,  int (*)(const void *, const void *))’ {aka ‘int(void *, long unsigned int,  long unsigned int,  int (*)(const void *, const void *))’}
  320 | int      mergesort(void *, size_t, size_t,
      |          ^~~~~~~~~
src/sortchecker.c:27:13: note: previous declaration of ‘mergesort’ with type ‘void(void *, size_t,  size_t,  int (*)(const void *, const void *))’ {aka ‘void(void *, long unsigned int,  long unsigned int,  int (*)(const void *, const void *))’}
   27 | EXPORT void mergesort(void *data, size_t n, size_t sz, cmp_fun_t cmp);
      |             ^~~~~~~~~
src/sortchecker.c: In function ‘heapsort’:
src/sortchecker.c:615:34: error: passing argument 5 of ‘qsort_common’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  615 |   qsort_common(data, n, sz, cmp, _real, &ctx);
      |                                  ^~~~~
      |                                  |
      |                                  int (*)(void *, size_t,  size_t,  int (*)(const void *, const void *)) {aka int (*)(void *, long unsigned int,  long unsigned int,  int (*)(const void *, const void *))}
src/sortchecker.c:588:33: note: expected ‘void (*)(void *, size_t,  size_t,  int (*)(const void *, const void *))’ {aka ‘void (*)(void *, long unsigned int,  long unsigned int,  int (*)(const void *, const void *))’} but argument is of type ‘int (*)(void *, size_t,  size_t,  int (*)(const void *, const void *))’ {aka ‘int (*)(void *, long unsigned int,  long unsigned int,  int (*)(const void *, const void *))’}
  588 |                          void (*real)(void *, size_t n, size_t sz, cmp_fun_t cmp),
      |                          ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/sortchecker.c: In function ‘mergesort’:
src/sortchecker.c:623:34: error: passing argument 5 of ‘qsort_common’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  623 |   qsort_common(data, n, sz, cmp, _real, &ctx);
      |                                  ^~~~~
      |                                  |
      |                                  int (*)(void *, size_t,  size_t,  int (*)(const void *, const void *)) {aka int (*)(void *, long unsigned int,  long unsigned int,  int (*)(const void *, const void *))}
src/sortchecker.c:588:33: note: expected ‘void (*)(void *, size_t,  size_t,  int (*)(const void *, const void *))’ {aka ‘void (*)(void *, long unsigned int,  long unsigned int,  int (*)(const void *, const void *))’} but argument is of type ‘int (*)(void *, size_t,  size_t,  int (*)(const void *, const void *))’ {aka ‘int (*)(void *, long unsigned int,  long unsigned int,  int (*)(const void *, const void *))’}
  588 |                          void (*real)(void *, size_t n, size_t sz, cmp_fun_t cmp),
      |                          ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
The return value can be used to check of the sort was successful.

Feel free to close this, I just wanted to report this in case you do want to fix this.

**Comment by yugr** [comment] 2024-12-22 09:31
Thank you very much for reporting this (and trying the tool). I believe the issue is fixed now and most of the tests seem to work.

It would be great to enable autotesting for BSD but sadly GH actions do not have BSD workers.

**Comment by 0-wiz-0** [comment] 2024-12-22 09:34
Thank you! I get to the linking step now:
```
cc -fPIC -shared -Wl,--no-allow-shlib-undefined -Wl,--warn-common -Wl,-O2 bin/sortchecker.o bin/proc_info.o bin/checksum.o bin/io.o bin/flags.o -ldl -o bin/libsortcheck.so
ld: cannot find -ldl: No such file or directory
```
The [`dl*()` family](https://man.netbsd.org/dlopen.3) lives in libc on NetBSD.

**Comment by 0-wiz-0** [comment] 2024-12-22 09:37
When I remove `-ldl` from the Makefile, it builds and I can run the tests.
There are many warning like this:
```
tests/test.sh: get_syslog: journalctl: not found
```
and three errors:
```
tests/sort_r_nonsym_1.c: In function ‘main’:
tests/sort_r_nonsym_1.c:21:3: warning: implicit declaration of function ‘qsort_r’; did you mean ‘qsort’? [-Wimplicit-function-declaration]
   21 |   qsort_r(aa, sizeof(aa), 1, cmp, &x);
      |   ^~~~~~~
      |   qsort
...
tests/test.sh: bin/a.out: not found
...
tests/syslog_1.c: syslog does not match pattern 'comparison function modifies data'
```

**Comment by 0-wiz-0** [comment] 2024-12-22 10:18
Btw, here's a workflow for [running CI on NetBSD](https://github.com/vmactions/netbsd-vm)

**Comment by yugr** [comment] 2024-12-22 10:25
> When I remove `-ldl` from the Makefile, it builds and I can run the tests.

Right, should be fixed now.

> There are many warning like this:
> 
> ```
> tests/test.sh: get_syslog: journalctl: not found
> ```

Script assumed that syslog is available which is not the case for BSD. Fixed now.

> tests/sort_r_nonsym_1.c:21:3: warning: implicit declaration of function ‘qsort_r’; did you mean ‘qsort’? [-Wimplicit-function-declaration]

It seems `qsort_r` function is not declared by default in stdlib.h on NetBSD. I couldn't repro this with my FreeBSD.

Maybe you could inspect `/usr/include/stdlib.h` to figure out what macro need to be defined to force this declaration? I can try installing NetBSD VM later or maybe there's some online machine I could use?

> tests/test.sh: bin/a.out: not found

Same, need NetBSD machine

> tests/syslog_1.c: syslog does not match pattern 'comparison function modifies data'

Same as before, syslog-ng not installed.

> Btw, here's a workflow for [running CI on NetBSD](https://github.com/vmactions/netbsd-vm)

Oh, that's nice, thank you!

**Comment by 0-wiz-0** [comment] 2024-12-22 10:45
NetBSD does not provide `qsort_r()` at all. I see that POSIX has some words about it, so I've filed [a NetBSD bug](https://gnats.netbsd.org/58931) report for that.
[sdf.org](https://sdf.org/?faq?BASICS?08) has public NetBSD machines online.

**Comment by yugr** [comment] 2024-12-22 11:24
> NetBSD does not provide `qsort_r()` at all. I see that POSIX has some words about it, so I've filed [a NetBSD bug](https://gnats.netbsd.org/58931) report for that.

Good, I disabled the test for NetBSD.

> [sdf.org](https://sdf.org/?faq?BASICS?08) has public NetBSD machines online.

Unfortunately public users are not allowed to compile.

**Comment by 0-wiz-0** [comment] 2024-12-22 11:37
I still see
```
tests/sort_r_nonsym_1.c: In function ‘main’:
tests/sort_r_nonsym_1.c:24:3: warning: implicit declaration of function ‘qsort_r’; did you mean ‘qsort’? [-Wimplicit-function-declaration]
   24 |   qsort_r(aa, sizeof(aa), 1, cmp, &x);
      |   ^~~~~~~
      |   qsort
ld: /tmp//ccMBnAhO.o: in function `main':
sort_r_nonsym_1.c:(.text+0xa1): undefined reference to `qsort_r'
tests/sort_r_nonsym_1.c: compilation failed
...
tests/syslog_1.c: syslog does not match pattern 'comparison function modifies data'
```

**Comment by yugr** [comment] 2024-12-22 12:03
Sorry, a silly mistake. Should work now.

**Closed as completed** 2024-12-22 12:48 UTC
Labels: bug

**Comment by yugr** [comment] 2024-12-30 08:09
> > Btw, here's a workflow for [running CI on NetBSD](https://github.com/vmactions/netbsd-vm)
> 
> Oh, that's nice, thank you!

Added Free/NetBSD runs: https://github.com/yugr/sortcheck/actions/workflows/bsd.yml

**Comment by 0-wiz-0** [comment] 2024-12-30 09:41
Great job, thanks!
